# Server Configurations
server:
  port: 8000



# Framework Configurations
app:
  auth:
    tokenSecret: Us#2lesf0237Eq
    expiredMs: 864000000  # 10 days
    freepass:
      enable: true
      masterToken: hst
  scheduler:
    poolSize: 5
  files:
    baseDirectory: ${user.home}/learning-hub

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.clozyxtm7nwy.ap-northeast-2.rds.amazonaws.com:3306/learning_hub
    username: hst
    password: hstqweQWE
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1