# Server Configurations
server:
  port: 8000



# Framework Configurations
app:
  auth:
    tokenSecret: Us#2lesf0237Eq
    expiredMs: 864000000  # 10 days
    freepass:
      enable: true
      masterToken: hst
  scheduler:
    poolSize: 5

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.219.16:3306/learning_hub?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Seoul
    username: hst
    password: hst123!@#
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true